[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x5a1092522ac6be6763657782e90133540f51b36fa6b12a2f40bbc4bafb58afaf'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]